services:
  # 1. Redis Database
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. Question Service
  question-service:
      build: ./services/question-service
      ports:
        - "8081:8081"
      volumes:
        - ./services/question-service:/usr/src/app
        - /usr/src/app/node_modules
        - ./services/question-service/serviceAccountKey.json:/usr/src/app/serviceAccountKey.json
  
  # 3. Matching Service
  matching-service:
    build: ./services/matching-service
    ports:
      - "8082:8082"
    environment:
      - REDIS_URL=redis://redis:6379
      - QUESTION_SERVICE_URL=http://question-service:8081
    depends_on:
      - redis
      - question-service

  # 4. Collaboration Service
  collaboration-service:
    build: ./services/collaboration-service
    ports:
      - "8084:8084"
  # 5. User Service
  user-service:
    build: 
      context: ./services/user-service
      dockerfile: Dockerfile
    volumes:
      - ./services/user-service:/usr/src/app
      - /usr/src/app/node_modules 
      - ./services/user-service/serviceAccountKey.json:/usr/src/app/serviceAccountKey.json
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    
  # 6. Frontend (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_MATCHING_SERVICE_URL=http://localhost:8082
    volumes:
      - ./frontend:/app
      - /app/node_modules # Don't overwrite node_modules with local ones
    depends_on:
      - matching-service
  
  # 7. API Gateway
  gateway:
    build: ./gateway
    ports:
      - "5001:5001"
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - MATCHING_SERVICE_URL=http://matching-service:8082
    restart: always
    depends_on:
      - user-service
      - matching-service
      - question-service
      - collaboration-service
      - frontend